# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be05a0b5aeb0f3ba753387dbaf5ae32c308d0ebcb0cf5dda24fcb837cdb66732577a3ac144c33c0e1f7113460f6178c9b855ebb6d16e5d79b42cbde507f6368

test:
  secret_key_base: f2c675d6e06896f85a5b94aab7b7d476193a42bd4bad53f570e56c8d1e61adcd39d1430f67cc4f5f9e7f1c6da4ba5b225ee6e476ce74da97076f72fb3ea8df3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
